services:
  db:
    #uses latest sql image
    build:
      #directory containing the dockerfile(docker uses this as a build context)
      context: db/.
    container_name: db
    ports:
      - "3306:3306"

  app:
    build:
      #directory containing the dockerfile(docker uses this as a build context)
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    #makes sure that the container that has the database runs first before our code container
    depends_on:
      - db
    ports:
      - "8080:8080"


